CREATE TABLE recipes (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(100) UNIQUE NOT NULL,
     description VARCHAR(500)
);

CREATE TABLE ingredients (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(100) NOT NULL,
     unit VARCHAR(50) NOT NULL,
     quantity NUMERIC(10,3) NOT NULL,
     recipe_id BIGINT NOT NULL,
     CONSTRAINT fk_ingredients_recipe
         FOREIGN KEY (recipe_id) REFERENCES recipes (id)
             ON DELETE CASCADE,
     CONSTRAINT uq_name_recipe UNIQUE (recipe_id, name),
     CONSTRAINT ck_quantity_positive CHECK(quantity > 0)
);

CREATE TABLE steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    step_number INTEGER NOT NULL,
    recipe_id BIGINT NOT NULL,
    CONSTRAINT fk_steps_recipe
       FOREIGN KEY (recipe_id) REFERENCES recipes (id)
           ON DELETE CASCADE,
    CONSTRAINT uq_step_number_recipe UNIQUE (recipe_id, step_number),
    CONSTRAINT ck_step_number_positive CHECK (step_number > 0)
);




