ALTER TABLE recipes ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE ingredients ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE steps ALTER COLUMN id DROP IDENTITY IF EXISTS;

CREATE SEQUENCE recipes_id_seq INCREMENT BY 50 OWNED BY recipes.id;
CREATE SEQUENCE steps_id_seq INCREMENT BY 50 OWNED BY steps.id;
CREATE SEQUENCE ingredients_id_seq INCREMENT BY 50 OWNED BY ingredients.id;