spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/recipe-book}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    dev.michaelgoldman.recipebookbackend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi.yaml
