spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    clean-disabled: true

logging:
  level:
    root: INFO
    dev.michaelgoldman.recipebookbackend: INFO

cors:
  allowed-origin-pattern: ${CORS_ALLOWED_ORIGIN_PATTERN}