spring:
  application:
    name: recipe-book-backend

  mvc:
    problemdetails:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:false}