spring:
  application:
    name: recipe-book-backend

  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:true}